codecov:
  branch: dev

coverage:
  range: 70..100
  round: down
  precision: 5

  ignore:
    - "docs/*"
    - "experiments/*"
    - "misc/*"
    - "test/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
