language: python
python: 3.6.4

env:
  global:
  - LIBRARY_PATH=/usr/local/lib
  - LD_LIBRARY_PATH=/usr/local/lib

matrix:
  include:
    - env: BUILD=tests
    - env: BUILD=docs

before_install: sudo .ci/travis-before-install.sh
install:  .ci/travis-install.sh
script: .ci/travis-script.sh
after_success: .ci/travis-after-success.sh
